constants:
  docker_container_name: ryu-sdn-1
  docker_image: mbyzhang/awareness
  docker_network: mas-network

containers:
- name: $docker_container_name
  hostname: $docker_container_name
  image: $docker_image
  volumes: 
    $base_dir++/ryu:
      bind: /scripts
      mode: ro
  command: /scripts/ryu_app start-foreground
  network: $docker_network
  remove: True
