#!/bin/bash

PID_FILE=/run/ryu-app.pid
BASE_DIR="$(dirname $0)"

start_foreground() {
      cd "$BASE_DIR"
      exec ryu run ryu.app.network_awareness.shortest_forwarding ryu.app.network_awareness.restful_server ryu.app.ofctl_rest --observe-links --k-paths=20 --weight=all
}

start() {
      start-stop-daemon --make-pidfile --pidfile "$PID_FILE" --startas "$PWD/$0" --chdir "$(dirname $0)" --background --start start-foreground
}

stop() {
      start-stop-daemon --remove-pidfile --pidfile "$PID_FILE" --stop --retry INT/30/TERM/30/KILL/5
}

case "$1" in
start)
      start
      ;;
start-fg | start-foreground)
      start_foreground
      ;;
stop)
      stop
      ;;
restart|reload)
      stop
      start
      ;;
*)
      echo $"Usage: $0 {start|stop|restart|reload|start-fg}"
      exit 1
esac

exit 0
